/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hellotwilio.hellotwilioengine;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.hellotwilio.hellotwilioengine//HelloTwilioWindow//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "HelloTwilioWindowTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "com.hellotwilio.hellotwilioengine.HelloTwilioWindowTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_HelloTwilioWindowAction",
        preferredID = "HelloTwilioWindowTopComponent"
)
@Messages({
  "CTL_HelloTwilioWindowAction=HelloTwilioWindow",
  "CTL_HelloTwilioWindowTopComponent=HelloTwilioWindow Window",
  "HINT_HelloTwilioWindowTopComponent=This is a HelloTwilioWindow window"
})
public final class HelloTwilioWindowTopComponent extends TopComponent {

  public HelloTwilioWindowTopComponent() {
    initComponents();
    setName(Bundle.CTL_HelloTwilioWindowTopComponent());
    setToolTipText(Bundle.HINT_HelloTwilioWindowTopComponent());

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    txtPhoneNumber = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtAccountSid = new javax.swing.JTextField();
    txtAuthToken = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtOutput = new javax.swing.JTextArea();
    jLabel4 = new javax.swing.JLabel();
    txtFromNumber = new javax.swing.JTextField();
    lblBody = new javax.swing.JLabel();
    txtBody = new javax.swing.JTextField();

    org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.jButton1.text")); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    txtPhoneNumber.setText(org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.txtPhoneNumber.text")); // NOI18N
    txtPhoneNumber.setName("txtPhoneNumber"); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.jLabel1.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.jLabel2.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.jLabel3.text")); // NOI18N

    txtAccountSid.setText(org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.txtAccoundSid.text")); // NOI18N
    txtAccountSid.setName("txtAccoundSid"); // NOI18N

    txtAuthToken.setText(org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.txtAuthToken.text")); // NOI18N
    txtAuthToken.setName("txtAuthToken"); // NOI18N

    txtOutput.setColumns(20);
    txtOutput.setRows(5);
    txtOutput.setName("txtOutput"); // NOI18N
    jScrollPane1.setViewportView(txtOutput);

    org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.jLabel4.text")); // NOI18N

    txtFromNumber.setText(org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.txtFromNumber.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(lblBody, org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.lblBody.text")); // NOI18N

    txtBody.setText(org.openide.util.NbBundle.getMessage(HelloTwilioWindowTopComponent.class, "HelloTwilioWindowTopComponent.txtBody.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButton1))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(jLabel2))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtAuthToken)
              .addComponent(txtAccountSid)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel4)
              .addComponent(lblBody))
            .addGap(53, 53, 53)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtBody)
              .addComponent(txtPhoneNumber)
              .addComponent(txtFromNumber))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtAccountSid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(txtAuthToken, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtFromNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtBody, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblBody))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private String targetUrl;

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    HttpURLConnection connection;
    URL url;

    try {
      String to = URLEncoder.encode(txtPhoneNumber.getText(), "UTF-8");
      String from = URLEncoder.encode(txtFromNumber.getText(), "UTF-8");
      String body = URLEncoder.encode(txtBody.getText(), "UTF-8");
      String urlParams = String.format("To=%1$s&From=%2$s&Body=%3$s", to, from, body);
      String auth = new String(Base64.getEncoder().encode((txtAccountSid.getText() + ":" + txtAuthToken.getText()).getBytes()));
      byte[] postData = urlParams.getBytes();
      int postDataLength = postData.length;

      targetUrl = String.format("https://api.twilio.com/2010-04-01/Accounts/%1$s/Messages", txtAccountSid.getText());

      url = new URL(targetUrl);

      connection = (HttpURLConnection) url.openConnection();
      connection.setRequestMethod("POST");
      connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
      connection.setRequestProperty("Content-Length", Integer.toString(postDataLength));
      connection.setRequestProperty("Authorization", "Basic " + auth);

      connection.setUseCaches(false);
      connection.setDoOutput(true);

      DataOutputStream wr = new DataOutputStream(connection.getOutputStream());
      wr.write(postData);
      wr.close();

      InputStream is = connection.getInputStream();
      BufferedReader br = new BufferedReader(new InputStreamReader(is));
      StringBuilder response = new StringBuilder();
      String line;

      while ((line = br.readLine()) != null) {
        response.append(line);
        response.append('\r');
      }

      br.close();

      txtOutput.setText(response.toString());

    } catch (Exception e) {
      e.printStackTrace();
      txtOutput.setText(e.getMessage());
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblBody;
  private javax.swing.JTextField txtAccountSid;
  private javax.swing.JTextField txtAuthToken;
  private javax.swing.JTextField txtBody;
  private javax.swing.JTextField txtFromNumber;
  private javax.swing.JTextArea txtOutput;
  private javax.swing.JTextField txtPhoneNumber;
  // End of variables declaration//GEN-END:variables
  @Override
  public void componentOpened() {
    // TODO add custom code on component opening
  }

  @Override
  public void componentClosed() {
    // TODO add custom code on component closing
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  void readProperties(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }
}
